apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
  finalizers:
    - kubernetes.io/pvc-protection
  name: prbz-overview-pvc
  labels:
    # remove the -pvc suffix later
    application: prbz-overview-pvc
    paas.redhat.com/appcode: SET-002

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

